---
collections:
  - ansible.utils
  - awx.awx
  - cisco.aci
  - cloud.terraform
  - community.aws
  - community.docker
  - community.general
  - containers.podman
  - infra.controller_configuration
  - netbox.netbox
