---
- name: Test playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Test useless_trivia module
      computacenter.ansible_community.useless_trivia:
        id: 8538ccb6853eb994e971ac1183ce49db
        # language: en
      register: output

    - name: Output module result
      ansible.builtin.debug:
        msg: '{{ output.trivia_text }}'
