---

- name: Demo playbook for Community Call about changes with Ansible Core 2.19+
  hosts: managed_nodes
  tasks:
    - name: Show hostname of managed node with ansible-core {{ ansible_version.full }}
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }}"

    - name: Output all facts when providing a variable with ansible-core {{ ansible_version.full }}
      ansible.builtin.debug:
        var: ansible_facts
      when: show_all_facts | default(false) | bool

    - name: Ensure inventory hostname and managed node hostname match with ansible-core {{ ansible_version.full }}
      ansible.builtin.assert:
        that:
          - ansible_hostname == inventory_hostname
        success_msg: "{{ inventory_hostname }} matches {{ ansible_hostname }}"
        fail_msg: "{{ inventory_hostname }} does not match {{ ansible_hostname }}!"
        quiet: false

    - name: Validate hostname with ansible-core {{ ansible_version.full }}
      ansible.builtin.assert:
        that:
          - ansible_hostname is defined and ansible_hostname | length > 0 and ansible_hostname == 'demo-node-instance1'
        quiet: false

    - name: Check for existence file on managed node with ansible-core {{ ansible_version.full }}
      ansible.builtin.stat:
        path: /etc/containers/regsitries.conf
      register: result
      failed_when: result.stat.exists is false

    - name: Get content of /etc/filesystems with ansible-core {{ ansible_version.full }}
      ansible.builtin.command:
        cmd: cat /etc/filesystems
      changed_when: false
      register: filesystems_output

    - name: Line by line output of first 7 lines from /etc/filesystems with ansible-core {{ ansible_version.full }}
      ansible.builtin.debug:
        msg: "{{ filesystems_output['stdout_lines'][item] }}"
      loop: "{{ range(0, 7) | list }}"

    - name: Loop with string manipulation with ansible-core {{ ansible_version.full }}
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ device_list | map('replace', 'test', 'prod') }}"
      vars:
        device_list:
          - test1
          - test2
          - test3

    - name: Output host report
      ansible.builtin.debug:
        msg: "{{ report_content }}"
      vars:
        report_content: "{{ lookup('template', 'template.j2') }}"
      when: report_content is not none and report_content | length > 0
