---

- name: Run automation against all virtual machines in the Frankfurt cluster
  hosts: cluster_DO-FRA1
  gather_facts: false
  tasks:
    - name: Gather bare minimum facts about the host
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
