---

- name: Output some cached facts
  hosts: podman_demo_instances
  gather_facts: false
  tasks:
    - name: Output some facts
      ansible.builtin.debug:
        msg:
          - "Distribution: {{ ansible_facts.distribution }}"
          - "Version: {{ ansible_facts.distribution_version }}"
